### ISSUE TITLE
An easy guide for hosting

### ISSUE THREAD

**Issue by Zanoxxx** [jaronpate/steam-idler#1]
i know literally nothing about hosting this type of thing and it will be awesome to get a guide for it. i tried googling for 3 hours but i cant make it work, i tried making a mongodb but nohting changed, is there an easy way to host this like on AWS or heroku or somethin similar, sorry for asking.
and sorry my english is really bad and my knowledge too.

**Comment by jaronpate** [comment]
I will be archiving this project and starting a new one. This is very old and poorly written code. I'll do my best to create a guide for the new one and make it simpler to host.
